### ISSUE TITLE
"illegal type argument for default precision qualifier"

### ISSUE THREAD

**Issue by epitron** [pyalot/craftscape#3]
I'm getting an error from this (and a number of your other) demo(s):

```
copy.shader: shader compile: 
ERROR: 0:4: 'float' : illegal type argument for default precision qualifier 
ERROR: 0:5: 'float' : illegal type argument for default precision qualifier 
ERROR: 0:6: 'float' : illegal type argument for default precision qualifier 
```

Other examples:

http://codeflow.org/webgl/trails/www/

```
code.js:2948
    Uncaught Shader Compile Error: ERROR: 0:3: 'float' : illegal type argument for default precision qualifier 
    ERROR: 0:4: 'float' : illegal type argument for default precision qualifier 
    ERROR: 0:5: 'float' : illegal type argument for default precision qualifier 
```

http://codeflow.org/entries/2013/feb/04/high-performance-js-heatmaps/#live-version

```
Shader Compile Error:
ERROR: 0:3: 'float' : illegal type argument for default precision qualifier
ERROR: 0:4: 'float' : illegal type argument for default precision qualifier
ERROR: 0:5: 'float' : illegal type argument for default precision qualifier
```

(I'm currently using Chromium v26.0.1410.43, and Linux nVidia drivers v313.26.)

**Comment by millerbd** [comment]
hi, also getting this error when using the heatmaps.

**Comment by pyalot** [comment]
Fixed: https://github.com/pyalot/craftscape/commit/f44b1fe84ce7ab9167051629adc7377b5056c40b
Fixed: https://github.com/pyalot/webgl-heatmap/commit/743e5d032b41a3928f4e9200b2233c4c1f56fa68
And Fixed: https://github.com/pyalot/webgl-trails/commit/45cdc43fd6087743c4e61e3c92ecd1c1259865ef
