### ISSUE TITLE
Blank white page (except for top & bottom) in Chrome and Firefox

### ISSUE THREAD

**Issue by poshaughnessy** [pyalot/craftscape#5]
Firstly, thanks for this - I still love this demo and still show it to people. I just tried showing it to another colleague though, and it no longer seems to work in Chrome of Firefox?

I'm getting a blank white page, except for the top links and instructions at the bottom.

The error in Firefox seems to be this one: 

webgl-debug.js:330:
Error: WebGL: A texture is going to be rendered as if it were black, as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a texture with a linear minification filter, which is not compatible with gl.FLOAT by default. Try enabling the OES_texture_float_linear extension if supported. 

In Chrome it says:

Uncaught /_UNKNOWN WebGL ENUM_/ 0x1280 drawArrays framework.js:17
Uncaught TypeError: Object #<Object> has no method 'match' st.f91390b971f60816047afb4d3819dd87.js:1
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.googleadservices.com') does not match the recipient window's origin ('http://www.google.com'). extension_properties.js:40
Uncaught TypeError: Object #<Object> has no method 'match' buttons.js:1
Uncaught TypeError: Object #<Object> has no method 'split' buttons.js:1
Uncaught TypeError: Object #<Object> has no method 'match' 

I guess the spec has probably changed a fair bit since you originally made the demo?

Cheers,
Peter

**Comment by pyalot** [comment]
The spec has changed a fair bit, and I gave it a shot for a couple hours to fix it, but couldn't manage. Due to the somewhat messyness of the code and new ideas I've had about doing it better, I've abandoned fixing this version, and hope to get a new rewrite of it up sometime.

**Comment by poshaughnessy** [comment]
Looking forward to that! Thanks Florian.

**Comment by tyronx** [comment]
A fix for this would be great :-)

**Comment by pyalot** [comment]
afaik this is no longer a problem (a fix has been contributed). Reopen if this is still an issue.
